import os

SUBSCRIPTION_ID = os.getenv("AZURE_SUBSCRIPTION_ID")
OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
OPENAI_KEY = os.getenv("AZURE_OPENAI_API_KEY") or os.getenv("AZURE_OPENAI_KEY")
OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")

AUTH_MODE = os.getenv("AUTH_MODE", "azure_ad")
AZURE_AD_TENANT_ID = os.getenv("AZURE_AD_TENANT_ID")
AZURE_AD_AUDIENCE = os.getenv("AZURE_AD_AUDIENCE")
AZURE_AD_CLIENT_ID = os.getenv("AZURE_AD_CLIENT_ID")
AZURE_AD_SCOPE = os.getenv("AZURE_AD_SCOPE")
